name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fect-depth: 0
        
    - name: Logging into Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: $ {{ secrets.DOCKER_PASSWORD }}


      run:
        echo "Logging into Docker"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Successful docker login"
        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
